version: "2.1"

services:
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: main.mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "0000"
    image: mysql
    ports:
      - "3306:3306"
  django:
    command: bash -c 'sleep 20; source /root/venv/bin/activate && while true; do python /root/main/manage.py runserver 0.0.0.0:8000; sleep 2; done'
    #command: bash
    container_name: main.django
    stdin_open: true
    tty: true
    image: insilicosp/docker_repository:django.v1
    ports:
      - "8000:8000"
    volumes:
      - ./:/root/main
